name: responsive_ui_design
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  # which supports multiple columns with rows of varying sizes
  flutter_staggered_grid_view: ^0.4.0
  # handle SVGs for Android, iOS, and Web.
  websafe_svg: ^2.1.1

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/Icons/
    - assets/images/
